logo: "/images/avatar.jpg"
title: Jesse Mathews
description: Journaling the journey
  <br><br>
  * Data Analyst<br>
  * Columbusite
  <br>
  <a href="https://www.linkedin.com/in/jesse-mathews-20662450/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-155328086-1
