google_analytics: <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-155328086-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-155328086-1');
</script>

theme: jekyll-theme-minimal
title: Jesse Mathews
description: Portfolio page
  <br><br>
  <a href="https://www.linkedin.com/in/jesse-mathews-20662450">View My LinkedIn Profile</a>
