logo: "/images/avatar.jpg"
title: Jesse Mathews
description: Columbusite, Data Analyst, Visual Communicator, Open Data Enthusiast.
  <br> Digital credentials:IBM Data Science Foundations Specialist
  <br>
  <a href="https://www.linkedin.com/in/jesse-mathews-20662450/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-155328086-1
