logo: "/images/avatar.jpg"
title: Jesse Mathews
description: :round_pushpin:Columbusite<br>
  Markdown is a way to style text on the web. You control the display of the document; formatting words as bold or italic, adding images.
  <br>
  <a href="https://www.linkedin.com/in/jesse-mathews-20662450/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-155328086-1
