title: Jesse Mathews
logo: "/images/MATH_FNL__Profile_logo_transparent.png?raw=true"
description: Portfolio page
  Data Analyst
  <br><br>
  <a href="https://www.linkedin.com/in/jesse-mathews-20662450/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-155328086-1
